### ISSUE TITLE
GLIBC_2.28 not found

### ISSUE THREAD

**Issue by giovannicaligaris** [Nitrux/znx#37]
Everytime I execute 

`sudo ./znx init /dev/sdX
`

I get a long error saying

```
sudo ./znx init /dev/sdb
znx: Wiping /dev/sdb. Please wait.
/dev/sdb: 8 bytes were erased at offset 0x00000052 (vfat): 46 41 54 33 32 20 20 20
/dev/sdb: 1 byte was erased at offset 0x00000000 (vfat): eb
/dev/sdb: 2 bytes were erased at offset 0x000001fe (vfat): 55 aa
Creating new GPT entries.
GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
Setting name!
partNum is 0
Setting name!
partNum is 1
The operation has completed successfully.
lsblk: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_znxZB3izu/usr/bin/../../lib/x86_64-linux-gnu/libudev.so.1)
lsblk: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_znxZB3izu/usr/bin/../../lib/x86_64-linux-gnu/libudev.so.1)
lsblk: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_znxZB3izu/usr/bin/../../lib/x86_64-linux-gnu/libudev.so.1)

```

Help please.

**Comment by UriHerrera** [comment]
I suppose this is happening with both releases? Can you try updating your version of libc6 to 2.33.1 in your distribution and comment if the issue still persists?.

**Comment by luis-lavaire** [comment]
> @luis-lavaire looks like the version of libc6 that should be included in the AppImage is being deleted during the build by this script as it is marked as a blacklisted file that should be expected to be present in the system.

Indeed. Those libraries that are deleted are supposed to exist in the system on which the AppImage is being run. Perhaps the only way that the application runs on any Linux system (which is the most outstanding goal of AppImages) is to delete [this](https://github.com/Nitrux/znx/blob/master/build.sh#L62-#L66) whole block of code from the build script. It would, of course, increase the size of the binaries, but functionality **will be granted**.

**Comment by UriHerrera** [comment]
We could also edit the script not to remove that library or any other file that we'd need.

**Comment by luis-lavaire** [comment]
Yeah, we could. But, as I mentioned, if we don't remove any dependency from the `Appdir`, we can ensure that the AppImage will work on any Linux system.

**Comment by anupam-git** [comment]
But that would increase the sizes by a huge margin. And it is not at all recommended to include libc in the Appimage. That should create a whole new bunch of errors and not recommended at all.

That is why, to make the appimages run on most of the systems, it is recommended to build the Appimage is the **oldest supported distro** so the dependencies depend on older version of libc ensuring seamless forward compatibility.

**Comment by UriHerrera** [comment]
@anupam-git It's being built in 19.04 because znx utilizes a newer binary of lsblk that can output the field `PATH` and only version 2.28+.

It's a "problem" right now because libc6 2.28 is a relatively new package in most distributions repositories, it won't be a problem as time goes by.

Another thing that I think we could do is to add the required libc6 debs to the script and use 16.04.

**Comment by UriHerrera** [comment]
@anupam-git It's being built in 19.04 because znx utilizes a newer package of util-linux (2.33.1).

It's a "problem" right now because of util-linux 2.33.1, as it depends on libc6 2.25, and it's a relatively new package in most distributions repositories; however, it won't be a problem as time goes by.

What we could do I think, is add the newer debs of util-linux and libc6 2.25+ to the build script.

**Comment by anupam-git** [comment]
As per me knowing, it will not work because of the same reason. Having a package depending on a newer libc while the system has an older libc will not work at all.

As far as I know, the idea for building on an older system is to make the dependencies depend on older libc and system libraries which are not included in the Appimage so the appimages works on every distro.

Let me take a look if I can come up with a solution.

Whatever it is, including libc in Appimage is a strict no and also building the Appimage on the latest distro is a strict no.

Let me take a look.

**Comment by luis-lavaire** [comment]
If you include the proper C library and set a proper `$LD_LIBRARY_PATH`, wouldn't the program load the correct library, and thus, work?

**Comment by anupam-git** [comment]
Here is a solution for building in Xenial and having the required `util-linux` version: 

Instead of installing `util-linux` from the xenial repository, use the following script to build util-linux :
```
apt update
apt install -y wget git autoconf gettext automake libtool-bin autopoint pkg-config libncurses5-dev

git clone https://github.com/karelzak/util-linux.git --depth 1 --branch stable/v2.33

$(
  cd util-linux

  ./autogen.sh 
  ./configure

  make -j$(nproc)
  make -j$(nproc) install
)

rm /lib/x86_64-linux-gnu/libsmartcols.so.1*
```

The resulting lsblk tool is having the required `PATH` column and should solve your problem.

**Comment by anupam-git** [comment]
@luis-lavaire @UriHerrera we should close this issue if solved already.
