### ISSUE TITLE
Add a template .INFO file.

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx#40]
This issue https://github.com/Nitrux/znx/issues/32 introduced a new method of updating the ISO images; however, it's undocumented, and as such, it's currently breaking existing deployments.

This is the output that znx currently displays.

```
uri@host:~$ sudo znx update /dev/nvme0n1 nitrux/development
znx: Updating nitrux/development.
mount: /tmp/tmp.rbrpz6dvMe: /dev/loop0 already mounted on /cdrom.
uri@host:~$ sudo znx --version
bac7525
```

**Comment by luis-lavaire** [comment]
That issue triggers because most distributions mount their ISO images in an old fashioned way (i.e. manually assigning loop devices to files, rather than letting `mount` handle that by itself).

Regarding the file's documentation, ATM, `znx` is just aware of one field: `UPDATE_URL`, which points to the URL that was previously stored in the volume descriptor field in the ISO image.

```
# This is a comment.

UPDATE_URL     http://my.fancy.server.org/path/to/file.zsync

# This field is also written to the file in the nitrux-iso-tool build script.

GIT_COMMIT  0123456
```

As seen, the syntax is very simple. Comments start with a `#`.

**Comment by luis-lavaire** [comment]
Bind-mounting the ISO image will fix the issue (not to be done manually; I'll make `znx` do that).

**Comment by luis-lavaire** [comment]
@UriHerrera, could you confirm the solution introduced in b7af160?

**Comment by UriHerrera** [comment]
Nope, znx gives an error that the .INFO file is missing, so previous images that don't have this file aren't updatable.

**Comment by UriHerrera** [comment]
In the latest commit to master I have uncommented the line 202 at https://github.com/Nitrux/znx/blob/master/appdir/znx

https://github.com/Nitrux/znx/blob/4f4996645655206da9fe6ab39379f8d8f10fe129/appdir/znx#L201-L217

If an ISO image that is deployed does not have the INFO file in it, they cannot be updated. This change affects our supported versions as well.

**Comment by UriHerrera** [comment]
Info file implemented in Nitrux (https://github.com/Nitrux/nitrux-iso-tool/issues/31).
