### ISSUE TITLE
znx break my own ubuntu server!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by sundogya** [Nitrux/znx#41]
After download nitrux iso file ,i burn it into my removable device , it cant find boot file. When i try use znx to take option , i download source code , and i notice that there is a build.sh file , and i run ./build.sh . Then my ubuntu server break , its service cant start.And now many of my sql data cant recovery.Please give me some help .

**Comment by UriHerrera** [comment]
> After download nitrux iso file ,i burn it into my removable device

In our FAQ and Compendium, we are very specific about not doing this. We very specifically mention that you should not flash the ISO file to a storage device and that you should use znx to make the deployment.

It's also very clearly indicated that the target device that it's used with znx will be wiped.

> When i try use znx to take option , i download source code , and i notice that there is a build.sh file , and i run ./build.sh 

We also very explicitly link to the AppImage binary, with clear-cut instructions on what steps to follow to use znx. We never, at any point, point users to the source code.

> Then my ubuntu server break , its service cant start.And now many of my sql data cant recovery.Please give me some help .

I'm very sorry to hear this. However, you do not mention any detailed information what you proceeded to do afterward. As such, this isn't an issue caused by or in relation to znx.
