### ISSUE TITLE
read: illegal option -n

### ISSUE THREAD

**Issue by stellarpower** [Nitrux/znx#56]
**Describe the bug**
Applies to the rewrite branch. I can't get any other version to work - they won't recognize a filename and try to download the image from a server with that name.

Can't get past square one due to the following error:
`/tmp/.mount_znx_reM4dnwG/znx: 362: read: Illegal option -n`
I think this may be due to the shebang in the file - using `sh` instead of `bash` usually causes these problems for me.

**To Reproduce**
`sudo ./znx_rewrite init`

**Desktop (please complete the following information):**
 - OS: Ubuntu Bionic (Mint)

**Comment by luis-lavaire** [comment]
Hi.

Please don't consider any branch other than `master` as stable, as they may be broken now and then.

I'm not understanding your issue very clearly: 

> they won't recognize a filename and try to download the image from a server with that name.

What do you mean by "not recognizing a file name"?

**Comment by stellarpower** [comment]
> Please don't consider any branch other than master as stable, as they may be broken now and then (specifically that branch is completely broken now).

Just hoping to give feedback for the current development, bugs for old code can be less useful than for new code :)

> What do you mean by "not recognizing a file name"?

    temp@Temp2 /tmp $ sudo ./znx deploy /dev/mmcblk0 nitrux/1_1_0 /tmp/nitrux-1.1.0-amd64.iso 
    znx: Deploying nitrux/1_1_0.
    Initializing download: /tmp/nitrux-1.1.0-amd64.iso
    Unable to connect to server :80: Nombre o servicio desconocido
    
    znx: Error: Failed to deploy nitrux/1_1_0.
    temp@Temp2 /tmp $ 

I downloaded the master and stable versions separately, they complain about not having SMARTCOLS_2.33, so I'm not sure what version the above was:

    temp@Temp2 /tmp $ sudo ./znx_master init /dev/mmcblk0
    znx: Wiping /dev/mmcblk0. Please wait.
    wipefs: /lib/x86_64-linux-gnu/libsmartcols.so.1: version `SMARTCOLS_2.33' not found (required by     wipefs)

**Comment by luis-lavaire** [comment]
> Just hoping to give feedback for the current development, bugs for old code can be less useful than for new code :)

Oh, thank you very much, in that case. :blush:

---

What I'm looking in that error message is that `znx` is trying to download a file that is present locally in the disk. That means that the checks are failing (I'm almost sure that that isn't happening in `development`).

OTOH, we are currently facing issues with packaging `znx` as an AppImage, because of missing dependencies (`znx` uses features of some programs that are not present in their older versions).

So, regarding the first point, I'll push the fix for it to the `master` ASAP. Regarding the second one, I already have plans for tuning the build script so the aforementioned issues fade.

**Comment by luis-lavaire** [comment]
Solved in a9d4f0c. See issue #55 for further details.

**Comment by stellarpower** [comment]
Thanks, will test it now for you :).
